# .github/workflows/binder-build.yml
name: local binder-readiness test

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  binder-check:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install repo2docker
        run: |
          python3 -m pip install --upgrade pip
          pip install jupyter-repo2docker

      - name: Build Binder image
        run: jupyter-repo2docker --no-run --debug .

