name: "Local Binder-style test (fixed)"

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  binder-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install repo2docker
        run: pip install --upgrade jupyter-repo2docker

      - name: Build image with repo2docker
        run: |
          # Pass NB_UID/NB_USER if you want to suppress the warnings:
          jupyter-repo2docker . \
            --no-run \
            --build-arg NB_UID=1000 \
            --build-arg NB_USER=jovyan \
            --image-name binder-test

      - name: Execute notebook inside the container
        run: |
          # Override ENTRYPOINT so we don't get tini trying to exec "--no-run"
          docker run --rm \
            --entrypoint "" \
            binder-test \
            jupyter nbconvert \
              --to notebook \
              --execute author_guideline_template.ipynb \
              --ExecutePreprocessor.timeout=600
